home/__init__.py
# -*- coding: utf-8 -*-
__author__ = 'QB'
# 定义蓝图(app/home/__init__.py)
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

home/views.py
# -*- coding: utf-8 -*-
__author__ = 'QB'
from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from app.home.forms import RegisterForm, LoginForm, UserdetailForm, PwdForm, CommentForm, SuggestForm
from app.models import User, Userlog, Preview, Tag, Movie, Comment, Moviecol, Suggest
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import db, app, rd
from functools import wraps
import urllib
import json
import uuid
import os
from datetime import datetime

# 分页个数
PAGE_COUNT = 10


# 登录装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user" not in session:
            # next页面为当前请求的url
            return redirect(url_for("home.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


# 根据API查询IP的地理位置
def admin_address(ipaddr):
    # ipaddr = json.load(urllib.request.urlopen('http://httpbin.org/ip'))['origin']
    # 组成查询ip地理位置的网址
    url = 'http://ip.taobao.com/service/getIpInfo.php?ip=%s' % (ipaddr)
    # 访问url地址, urlobject是<type 'instance'>对象；
    urlobject = urllib.request.urlopen(url)
    urlcontent = urlobject.read()
    res = json.loads(urlcontent)
    # print(res)
    # 显示查询结果
    # ip = res['data']['ip']
    address = res['data']['country'] + res['data']['region'] + res['data']['city'] + " " + res['data']['isp']
    return address


# 登录：调用蓝图(app/home/views.py)
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        users = []
        # user = User.query.filter_by(phone=data['name']).first()
        users.append(User.query.filter_by(name=data['name']).first())
        users.append(User.query.filter_by(email=data['name']).first())
        users.append(User.query.filter_by(phone=data['name']).first())
        print(users)
        # 另一种方法是先去除列表中的None，在进行判断
        for user in users:
            if user:
                if not user.check_pwd(data['pwd']):
                    # flash("密码不正确！", "err")
                    flash("登录名或登录密码不正确！", "err")
                    return redirect(url_for("home.login"))
                session["user"] = user.name
                session["user_id"] = user.id
                ip = request.remote_addr
                address = admin_address(ip)
                userlog = Userlog(
                    user_id=user.id,
                    # ip=request.remote_addr
                    ip=ip,
                    address=address,
                )
                db.session.add(userlog)
                db.session.commit()
                return redirect(url_for("home.user"))
        # flash("用户不存在，请重新输入!", "err")
        flash("登录名或登录密码不正确!", "err")
        return redirect(url_for("home.login"))
    return render_template('home/login.html', form=form)


# 退出
@home.route('/logout/')
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    # 重定向到home模块下的登录
    return redirect(url_for('home.login'))


# 会员注册
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功！", "ok")
    return render_template('home/register.html', form=form)


# 会员中心个人资料
@home.route('/user/', methods=['GET', 'POST'])
@user_login_req
def user():
    form = UserdetailForm()
    user = User.query.get(int(session['user_id']))
    # 修改会员名之后需要重新获取user.name
    if session["user"] != user.name:
        session["user"] = user.name
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if not os.path.exists(app.config['FC_DIR']):
            os.makedirs(app.config['FC_DIR'])
            os.chmod(app.config['DC_DIR'], 'rw')
        # 上传头像
        if form.face.data != '':  # 说明已经重新上传了头像
            if user.face is not None:
                # 如果有头像，删除本地的头像。保存新的头像在本地
                if os.path.exists(app.config['FC_DIR'] + user.face):
                    os.remove(app.config['FC_DIR'] + user.face)
                    print("user.face:" + app.config['FC_DIR'] + user.face)
            file_face = secure_filename(form.face.data.filename)
            user.face = change_filename(file_face)
            form.face.data.save(app.config['FC_DIR'] + user.face)

        # 会员名、邮箱、手机号码有可能重复
        name_count = User.query.filter_by(name=data['name']).count()
        if data['name'] != user.name and name_count == 1:
            flash("会员名已经存在，请重新编辑", "err")
            return redirect(url_for("home.user"))

        email_count = User.query.filter_by(email=data['email']).count()
        if data['email'] != user.email and email_count == 1:
            flash("邮箱已经存在，请重新编辑", "err")
            return redirect(url_for("home.user"))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if data['phone'] != user.phone and phone_count == 1:
            flash("手机号码已经存在，请重新编辑", "err")
            return redirect(url_for("home.user"))

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        db.session.add(user)
        db.session.commit()
        flash("修改成功！", "ok")
        return redirect(url_for("home.user"))
    return render_template('home/user.html', form=form, user=user)


# ta主页及动态
@home.route('/user/<int:id>/<int:page>/', methods=['GET'])
def user_info(id=None, page=None):
    user = User.query.get_or_404(int(id))
    if page is None:
        page = 1
    # 电影评论个数
    comment_count = Comment.query.join(
        User
    ).filter(
        User.id == user.id
    ).count()
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Comment.movie_id,
        User.id == user.id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=PAGE_COUNT)
    return render_template('home/userinfo.html', user=user, comment_count=comment_count, page_data=page_data)


# 修改密码
@home.route('/pwd/', methods=['GET', 'POST'])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session['user']).first()
        if not user.check_pwd(data['old_pwd']):
            flash("旧密码不正确！", "err")
            return redirect(url_for("home.pwd"))
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for("home.logout"))
    return render_template('home/pwd.html', form=form)


# 评论记录
@home.route('/comments/<int:page>/')
@user_login_req
def comments(page=None):
    if page is None:
        page = 1
    # 电影评论个数
    comment_count = Comment.query.join(
        User
    ).filter(
        User.id == session['user_id']
    ).count()
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Comment.movie_id,
        User.id == session["user_id"]
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=PAGE_COUNT)
    return render_template('home/comments.html', comment_count=comment_count, page_data=page_data)


# 登录日志
@home.route('/loginlog/<int:page>/', methods=['GET'])
@user_login_req
def loginlog(page=None):
    # 登录次数
    loginlog_count = Userlog.query.join(
        User
    ).filter(
        User.id == session['user_id']
    ).count()
    if page is None:
        page = 1
    page_data = Userlog.query.filter_by(
        user_id=int(session["user_id"])
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=PAGE_COUNT)
    return render_template('home/loginlog.html', loginlog_count=loginlog_count, page_data=page_data)


# 添加电影收藏
@home.route("/moviecol/add/", methods=["GET"])
@user_login_req
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    moviecol = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid),
    ).count()
    # 已经收藏
    if moviecol == 1:
        data = dict(ok=0)
    # 未收藏
    if moviecol == 0:
        moviecol = Moviecol(
            user_id=int(uid),
            movie_id=int(mid),
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    return json.dumps(data)


# 电影收藏
@home.route('/moviecol/<int:page>')
@user_login_req
def moviecol(page=None):
    if page is None:
        page = 1
    # 电影收藏个数
    moviecol_count = Moviecol.query.join(
        User
    ).filter(
        User.id == session['user_id']
    ).count()
    page_data = Moviecol.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Moviecol.movie_id,
        User.id == session['user_id']
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=PAGE_COUNT)
    return render_template('home/moviecol.html', moviecol_count=moviecol_count, page_data=page_data)


# 网站建议
@home.route('/suggest/', methods=['GET', 'POST'])
@user_login_req
def suggest_add():
    form = SuggestForm()
    if form.validate_on_submit():
        data = form.data
        suggest = Suggest(
            user_id=session['user_id'],
            title=data['title'],

templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>小花椒微视频</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block css %}
        {#  CSS数据块  #}
    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:40px;margin-top: -10px;">&nbsp;小花椒
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入视频名称" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;首页</a>
                </li>
                {% if "user" not in session %}
                    <li>
                        <a id="btn-exit" class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a id="btn-exit" class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                {% else %}
                    <li>
                        <a id="btn-log" class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ session['user'] }}</a>
                    </li>
                    <li>
                        <a id="btn-log" class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %} {% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2018&nbsp;qinbin.xhuajiao.top&nbsp;桂ICP备 18006025号-1
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })
</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
         $("#do_search").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for("home.search",page=1) }}?key=" + key
        })
    });
</script>
{% block js %}
{#js数据块#}
{% endblock %}
</body>
</html>

templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏视频
        </a>
        <a id="m-6" href="{{ url_for('home.suggest_add') }}" class="list-group-item">
            <span class="glyphicon glyphicon-fire"></span>&nbsp;网站建议
        </a>
    </div>
</div>

templates/home/play.html
{% extends 'home/home.html' %}
{% import "ui/comment_page.html" as pg %}

{% block css %}
    <!--播放页面-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='jwplayer/skins/stormtrooper.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/ueditor.config.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/ueditor.all.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/lang/zh-cn/zh-cn.js') }}"></script>
    <script>
        SyntaxHighlighter.all();
    </script>
    <!--播放页面-->
    <style>
     .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }
    .container2{
            margin-top:76px
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div id="moviecontainer"></div>
        </div>
        <div class="col-md-4" style="height:500px;">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title" style="display:inline;"><span class="glyphicon glyphicon-facetime-video"></span>&nbsp;视频介绍</h3>
                    <a href="{{ url_for('home.video',id=movie.id,page=1) }}" class="label label-danger" style="font-size: 14px">
                    切换弹幕播放</a>
                </div>
                <div class="panel-body" style="height:459px;overflow:auto;">
                    <table class="table">
                        <tr>
                            <td style="width:30%;color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-film"></span>&nbsp;片名
                            </td>
                            <td>{{ movie.title }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-tag"></span>&nbsp;标签
                            </td>
                            <td>{{ movie.tag.name }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-time"></span>&nbsp;片长
                            </td>
                            <td>{{ movie.length }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-map-marker"></span>&nbsp;地区
                            </td>
                            <td>{{ movie.area }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-star"></span>&nbsp;星级
                            </td>
                            <td>
                                <div>
                                    {% for val in range(1,movie.star+1) %}
                                    <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    {% endfor %}
                                    {% for val in range(1,5-movie.star+1) %}
                                    <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-calendar"></span>&nbsp;上映时间
                            </td>
                            <td>{{ movie.release_time }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-play"></span>&nbsp;播放次数
                            </td>
                            <td>{{ movie.playnum }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论数量
                            </td>
                            <td>{{ movie.commentnum }}</td>
                        </tr>
                        <tr>
                            <td style="color:#ccc;font-weight:bold;">
                                <span class="glyphicon glyphicon-picture"></span>&nbsp;视频介绍
                            </td>
                            <td>{{ movie.info }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12" style="margin-top:6px;">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span>&nbsp;视频评论</h3>
                </div>
                <div class="panel-body">
                    {% if "user" not in session %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true"></span>
                                <span class="sr-only">Close</span>
                            </button>
                            <strong>请先<a href="{{ url_for('home.login') }}" target="_blank" class="text-info">登录</a>，才可参与评论！</strong>
                        </div>
                    {% endif %}

                    {% if "user" in session %}
                        {% for msg in get_flashed_messages(category_filter=["ok"]) %}
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                </button>
                                <h4><i class="icon fa fa-check"></i>{{ msg }}</h4>
                            </div>
                        {% endfor %}
                        {% for msg in get_flashed_messages(category_filter=["err"]) %}
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                </button>
                                <h4><i class="icon fa fa-ban"></i>{{ msg }}</h4>
                            </div>
                        {% endfor %}
                    <form role="form" style="margin-bottom:6px;" method="post">
                        <div class="form-group">
                            <div>
                                <label for="input_content">{{ form.content.label }}</label>
{#                                <textarea id="input_content"></textarea>#}
                                {{ form.content }}
                            </div>
                            {% for err in form.content.errors %}
                                <div class="col-md-12">
                                    <p style="color: red">{{ err }}</p>
                                </div>
                            {% endfor %}
                        </div>
{#                        <a class="btn btn-success" id="btn-sub"><span class="glyphicon glyphicon-edit"></span>&nbsp;提交评论</a>#}
                        {{ form.csrf_token }}
                        {{ form.submit }}
                        &nbsp;
                        <a class="btn btn-danger" id="btn-col"><span class="glyphicon glyphicon-heart"></span>&nbsp;收藏视频</a>
                    </form>
                        {#通过ajax异步方法添加视频收藏#}
                        <div class="col-md-12">
                            <h4 style="color:green" id="show_col_msg"></h4>
                        </div>
                        <div class="clearfix"></div>
                    {% endif %}
                    <ol class="breadcrumb" style="margin-top:6px;">
                        <li>全部评论({{ movie.commentnum }})</li>
                    </ol>
                    <ul class="commentList">
                        {% for v in page_data.items %}
                        <li class="item cl">
                            <a href="{{ url_for("home.user_info",id=v.user.id,page=1) }}" target="_blank">
                                <i class="avatar size-L radius">
                                    {% if v.user.face %}
                                        <img alt="50x50" src="{{ url_for('static',filename='uploads/users/'+v.user.face) }}"
                                             class="img-circle" style="border:1px solid #abcdef;width: 50px;">
                                    {% else %}
                                        <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;width: 50px;">
                                    {% endif %}
                                </i>
                            </a>
                            <div class="comment-main">
                                <header class="comment-header">
                                    <div class="comment-meta">
                                        <a class="comment-author" href="{{ url_for("home.user_info",id=v.user.id,page=1) }}" target="_blank">
                                            {{ v.user.name }}
                                        </a>
                                        评论于
                                        <time title="{{ v.addtime }}" datetime="{{ v.addtime }}">{{ v.addtime }}</time>
                                    </div>
                                </header>
                                <div class="comment-body">
                                    <p>{{ v.content | safe }}</p>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="col-md-12 text-center">
                        {% if movie.commentnum %}
                            {{ pg.page(page_data,'home.play',movie.id) }}
                        {% else %}
                            <p>还没有评论，快来第一个评论吧！</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!--播放页面-->
    <script src="{{ url_for('static',filename='jwplayer/jwplayer.js') }}"></script>
    <script>
    var ue = UE.getEditor('input_content',{
        toolbars: [
            [ 'emotion', 'link']
        ],
        initialFrameWidth:"100%",
        initialFrameHeight:"100",
    });
    </script>
    <script type="text/javascript">
        jwplayer.key = "P9VTqT/X6TSP4gi/hy1wy23BivBhjdzVjMeOaQ==";
    </script>
    <script type="text/javascript">
        jwplayer("moviecontainer").setup({
            flashplayer: "{{ url_for('static',filename='jwplayer/jwplayer.flash.swf') }}",
            playlist: [{
                file: "{{ url_for('static',filename='uploads/'+movie.url) }}",
                title: "{{ movie.title }}"
            }],
            modes: [{
                type: "html5"
            }, {
                type: "flash",
                src: "{{ url_for('static',filename='jwplayer/jwplayer.flash.swf') }}"
            }, {
                type: "download"
            }],
            skin: {
                name: "vapor"
            },
            "playlist.position": "left",
            "playlist.size": 400,
            height: 500,
            width: 774,
        });
    </script>
    <!--播放页面-->
    <script>
        $(document).ready(function () {
            {#为btn-col 设置点击事件，获取当前的movieid，获取当前的用户。#}
            $("#btn-col").click(function () {
                var mid = {{ movie.id }};
                var uid = {{ session['user_id'] }};
                {#使用ajax，提交的地址。#}
                $.ajax({
                    url: "{{ url_for('home.moviecol_add') }}",
                    type: "GET",/*type:get,提交的数据，返回的数据类型json。*/
                    data: "mid=" + mid + "&uid=" + uid,
                    dataType: "json",/*成功之后的处理函数res接收返回的json对象*/
                    success: function (res) {
                        if (res.ok == 1) {
                            $("#show_col_msg").empty();
                            $("#show_col_msg").append("收藏成功！");
                        } else {
                            $("#show_col_msg").empty();
                            $("#show_col_msg").append("已经收藏！");
                        }
                    }
                })
            });
        });
    </script>
{% endblock %}

templates/home/search.html
{% extends 'home/home.html' %}
{% import 'ui/search_page.html' as pg %}

{% block css %}
    <style>
        .container2{
            margin-top:76px
        }
    </style>
{% endblock %}
{% block content %}
<!--内容-->
 <div class="row">
    <div class="col-md-12">
         <ol class="breadcrumb" style="margin-top:6px;">
            {% if movie_count == 0 %}
                <li>没有找到任何与“{{ key }}”有关的视频资源</li>
            {% elif key %}
                <li>与“{{ key }}”有关的视频资源，共{{ movie_count }}部</li>
            {% else %}
                 <li>本站所有视频资源，共{{ movie_count }}部</li>
            {% endif %}
        </ol>
    </div>
    <div class="col-md-12">
        {% for v in page_data.items %}
        <div class="media">
            <div class="media-left">
                <a href="{{ url_for('home.video',id=v.id,page=1) }}">
                    <img class="media-object" style="width: 131px;height: 83px;" src="{{ url_for('static',filename='uploads/'+v.logo) }}" alt="{{ v.title }}">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="{{ url_for('home.video',id=v.id,page=1) }}" style="color: #000000;text-decoration:none; ">{{ v.title }}</a>
                    <a href="{{ url_for('home.video',id=v.id,page=1) }}" class="label label-primary pull-right">
                    <span class="glyphicon glyphicon-play"></span>播放视频</a>
                </h4>
                {{ v.info }}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-12 text-center">
        {% if movie_count %}
            {{ pg.page(page_data,'home.search') }}
        {% endif %}
    </div>
</div>
<!--内容-->
{% endblock %}